version: '3.8'

services:
  flipflops:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flipflops
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./documents:/app/documents:ro
      - ./config.ini:/app/config.ini
    env_file: 
      - .env
    environment:
      - TZ=America/Sao_Paulo
    command: --log-level INFO
    tty: true
    stdin_open: true
